language: python
python:
  - "3.6"
install:
  - pip install pip-tools
  - pip-compile --output-file ~/requirements-dev.txt requirements/requirements-dev.in
  - pip install -r ~/requirements-dev.txt
  # Output requirements for deployed environment
  - pip-compile --output-file requirements.txt requirements/requirements-dev.in
  - npm install -g serverless
  - npm install
script:
  - pytest test_handler.py
  - serverless deploy --stage staging
    # deploy:
    #   provider: script
    #   script: serverless deploy --stage staging
    #   on:
    #     branch: master
